// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eWellness.Core;

#nullable disable

namespace eWellness.DL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250213163846_change-seeds-date")]
    partial class changeseedsdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eWellness.Core.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("eWellness.Core.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialOfferId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SpecialOfferId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7622),
                            EndTime = new DateTime(2025, 2, 14, 19, 38, 44, 422, DateTimeKind.Local).AddTicks(7628),
                            IsDeleted = false,
                            Notes = "Demo note",
                            ServiceId = 1,
                            StartTime = new DateTime(2025, 2, 14, 18, 38, 44, 422, DateTimeKind.Local).AddTicks(7640),
                            Status = "COMPLETED",
                            TotalPrice = 40m,
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7625)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7647),
                            EndTime = new DateTime(2025, 2, 15, 19, 38, 44, 422, DateTimeKind.Local).AddTicks(7651),
                            IsDeleted = false,
                            Notes = "Demo note",
                            ServiceId = 1,
                            StartTime = new DateTime(2025, 2, 15, 18, 38, 44, 422, DateTimeKind.Local).AddTicks(7655),
                            Status = "RESERVED",
                            TotalPrice = 40m,
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7649)
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMember")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAppointment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MembershipExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalAppointments")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6854),
                            IsDeleted = false,
                            IsMember = true,
                            LastAppointment = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipExpirationDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            TotalAppointments = 0,
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6850),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6869),
                            IsDeleted = false,
                            IsMember = true,
                            LastAppointment = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipExpirationDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            TotalAppointments = 0,
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6866),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6942),
                            IsDeleted = false,
                            Position = "Admin",
                            Salary = 5000m,
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6938),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("eWellness.Core.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 40m,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7720),
                            Date = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7726),
                            Fees = 0m,
                            IsDeleted = false,
                            PaymentMethodId = 3,
                            TransactionId = "pi_import_test",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7722)
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7471),
                            Description = "Mastercard cards",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mastercard",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7465)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7483),
                            Description = "Visa cards",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Visa",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7479)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7491),
                            Description = "American Express kartice",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "AMEX",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7488)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7499),
                            Description = "Diners Club cards",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Diners",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7496)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7507),
                            Description = "Discovery cards",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Discovery",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7504)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7521),
                            Description = "Voucher payments",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Voucher",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7518)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7529),
                            Description = "Pay by bank transfer",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Virman",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7526)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7537),
                            Description = "Cash payment",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cash",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7534)
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7178),
                            Description = "Massage of the whole body for an hour",
                            Duration = 60,
                            ImageUrl = "https://i1.sndcdn.com/artworks-000135911201-ryi7ns-t500x500.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Full body massage",
                            Price = 40m,
                            ServiceCategoryId = 1,
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7181)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7191),
                            Description = "Sauna visit for half an hour",
                            Duration = 30,
                            ImageUrl = "https://i1.sndcdn.com/artworks-000135911201-ryi7ns-t500x500.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Sauna",
                            Price = 10m,
                            ServiceCategoryId = 3,
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7193)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7199),
                            Description = "Maderotherapy",
                            Duration = 30,
                            ImageUrl = "https://i1.sndcdn.com/artworks-000135911201-ryi7ns-t500x500.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Maderotherapy",
                            Price = 50m,
                            ServiceCategoryId = 2,
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7201)
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 417, DateTimeKind.Local).AddTicks(9444),
                            Description = "Various face and body massages",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Massage",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 417, DateTimeKind.Local).AddTicks(9439)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 417, DateTimeKind.Local).AddTicks(9456),
                            Description = "Various maderotherapies",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Maderotherapy",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 417, DateTimeKind.Local).AddTicks(9453)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 417, DateTimeKind.Local).AddTicks(9463),
                            Description = "Spa spaces",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spa",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 417, DateTimeKind.Local).AddTicks(9460)
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.SpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OfferExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SpecialOffers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7091),
                            Description = "Get three massages for the price of two",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "2 + 1",
                            OfferExpirationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7094)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7109),
                            Description = "Get seven sauna visits for the price of five",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "5 + 2",
                            OfferExpirationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7111)
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.Tip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Tips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7008),
                            CreatedByUserId = 1,
                            Description = "Welcome to the app, enjoy it!",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Enjoy :)",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7010)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7020),
                            CreatedByUserId = 1,
                            Description = "Cold baths strengthen immunity and improve blood flow.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cold baths brrr",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(7022)
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Test address no1",
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6657),
                            DateOfBirth = new DateTime(2005, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6691),
                            Email = "desktop",
                            EmergencyContactName = "N/A",
                            EmergencyContactPhone = "N/A",
                            Gender = "M",
                            IsDeleted = false,
                            Name = "Desktop App",
                            PasswordHash = "RpcvQ2cT/s7O3VKSuCaHOmS9HtVFOmpEl4ddT4TufDaSrRAZ",
                            PasswordSalt = "RpcvQ2cT/s7O3VKSuCaHOg==",
                            Phone = "0000000000",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6685)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Test address no2",
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6714),
                            DateOfBirth = new DateTime(2003, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6718),
                            Email = "mobile",
                            EmergencyContactName = "N/A",
                            EmergencyContactPhone = "N/A",
                            Gender = "M",
                            IsDeleted = false,
                            Name = "Mobile App",
                            PasswordHash = "RpcvQ2cT/s7O3VKSuCaHOmS9HtVFOmpEl4ddT4TufDaSrRAZ",
                            PasswordSalt = "RpcvQ2cT/s7O3VKSuCaHOg==",
                            Phone = "0000000000",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6716)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Test address no1",
                            CreatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6724),
                            DateOfBirth = new DateTime(2001, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6729),
                            Email = "test_client",
                            EmergencyContactName = "N/A",
                            EmergencyContactPhone = "N/A",
                            Gender = "M",
                            IsDeleted = false,
                            Name = "Test Client",
                            PasswordHash = "RpcvQ2cT/s7O3VKSuCaHOmS9HtVFOmpEl4ddT4TufDaSrRAZ",
                            PasswordSalt = "RpcvQ2cT/s7O3VKSuCaHOg==",
                            Phone = "0000000000",
                            UpdatedAt = new DateTime(2025, 2, 13, 17, 38, 44, 422, DateTimeKind.Local).AddTicks(6726)
                        });
                });

            modelBuilder.Entity("eWellness.Core.Models.ActivityLog", b =>
                {
                    b.HasOne("eWellness.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eWellness.Core.Models.Appointment", b =>
                {
                    b.HasOne("eWellness.Core.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("eWellness.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("eWellness.Core.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eWellness.Core.Models.SpecialOffer", "SpecialOffer")
                        .WithMany()
                        .HasForeignKey("SpecialOfferId");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Service");

                    b.Navigation("SpecialOffer");
                });

            modelBuilder.Entity("eWellness.Core.Models.Client", b =>
                {
                    b.HasOne("eWellness.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eWellness.Core.Models.Employee", b =>
                {
                    b.HasOne("eWellness.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eWellness.Core.Models.Invoice", b =>
                {
                    b.HasOne("eWellness.Core.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("eWellness.Core.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("eWellness.Core.Models.Payment", b =>
                {
                    b.HasOne("eWellness.Core.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("eWellness.Core.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.Navigation("Appointment");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("eWellness.Core.Models.Service", b =>
                {
                    b.HasOne("eWellness.Core.Models.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("eWellness.Core.Models.Tip", b =>
                {
                    b.HasOne("eWellness.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
